/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/parts/cpu`; params?: Router.UnknownInputParams; } | { pathname: `/parts/cpu_cooler`; params?: Router.UnknownInputParams; } | { pathname: `/parts/fonte`; params?: Router.UnknownInputParams; } | { pathname: `/parts/gabinete`; params?: Router.UnknownInputParams; } | { pathname: `/parts/gpu`; params?: Router.UnknownInputParams; } | { pathname: `/parts/motherboard`; params?: Router.UnknownInputParams; } | { pathname: `/parts/ram`; params?: Router.UnknownInputParams; } | { pathname: `/parts/ssd`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/modal` | `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/cpu`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/cpu_cooler`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/fonte`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/gabinete`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/gpu`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/motherboard`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/ram`; params?: Router.UnknownOutputParams; } | { pathname: `/parts/ssd`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/modal${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/parts/cpu${`?${string}` | `#${string}` | ''}` | `/parts/cpu_cooler${`?${string}` | `#${string}` | ''}` | `/parts/fonte${`?${string}` | `#${string}` | ''}` | `/parts/gabinete${`?${string}` | `#${string}` | ''}` | `/parts/gpu${`?${string}` | `#${string}` | ''}` | `/parts/motherboard${`?${string}` | `#${string}` | ''}` | `/parts/ram${`?${string}` | `#${string}` | ''}` | `/parts/ssd${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/parts/cpu`; params?: Router.UnknownInputParams; } | { pathname: `/parts/cpu_cooler`; params?: Router.UnknownInputParams; } | { pathname: `/parts/fonte`; params?: Router.UnknownInputParams; } | { pathname: `/parts/gabinete`; params?: Router.UnknownInputParams; } | { pathname: `/parts/gpu`; params?: Router.UnknownInputParams; } | { pathname: `/parts/motherboard`; params?: Router.UnknownInputParams; } | { pathname: `/parts/ram`; params?: Router.UnknownInputParams; } | { pathname: `/parts/ssd`; params?: Router.UnknownInputParams; };
    }
  }
}
